# Generated by Django 5.2.3 on 2026-03-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_review_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='home_banners/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='home_banners/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
