# Generated by Django 5.2.3 on 2026-03-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
