# Generated by Django 5.2.3 on 2026-03-19 11:29

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Name')),
                ('review', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
