# Generated by Django 5.2.3 on 2026-03-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
